-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    id integer,
    "firstName" character varying,
    "lastName" character varying,
    gender "char",
    level character varying
);

CREATE TABLE IF NOT EXISTS public.songs
(
    id character varying,
    title character varying,
    "artistID" character varying,
    year integer,
    duration numeric,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.artists
(
    id character varying,
    name character varying,
    location character varying,
    latitude numeric,
    longitude numeric,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."time"
(
    "startTime" bigint,
    hour integer,
    day integer,
    weekday integer,
    month integer,
    year integer
);

CREATE TABLE IF NOT EXISTS public.songplays
(
    id integer,
    start_time bigint,
    "userID" integer,
    level character varying,
    "songID" character varying,
    "artistID" character varying,
    "sessionID" integer,
    location character varying,
    "userAgent" character varying,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.songplays
    ADD CONSTRAINT "artistsFK" FOREIGN KEY ("artistID")
    REFERENCES public.artists (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.songplays
    ADD CONSTRAINT "songsFK" FOREIGN KEY ("songID")
    REFERENCES public.songs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;